### PR TITLE
Fixed the bug in CacheConfigMetricsCollector

### LINKED ISSUE #644: [BUG]org.opensearch.performanceanalyzer.collectors.CacheConfigMetricsCollector$CacheMaxSizeStatus
**What is the bug?**
Since upgrading from 2.12 to 2.13 i see the below WARN messages spamming the logs
Json Mapping Error: Cannot invoke “java.lang.Long.longValue()” because “this.cacheMaxSize” is null (through reference chain: org.opensearch.performanceanalyzer.collectors.CacheConfigMetricsCollector$CacheMaxSizeStatus[“Cache_MaxSize”])

**How can one reproduce the bug?**
install 2.13

**What is the expected behavior?**
no errors logged

**What is your host/environment?**
opensearch 2.13 container

### PR DESCRIPTION
**Pull request by atharvasharma61**
**Is your feature request related to a problem? Please provide an existing Issue # , or describe.**
Resolves #644 

Metrics are being emitted as expected:
```
^cache_config
{"current_time":1717142304989}
{"CacheType":"field_data_cache","Cache_MaxSize":-1}
{"CacheType":"shard_request_cache","Cache_MaxSize":10737418}$
```

**Describe the solution you are proposing**
Tiered Caching has introduced a new ICache interface which has an OnHeap implementation which actually stores the Cache field now. We had to update the logic to how to get the cache field. Relevant PR: https://github.com/opensearch-project/OpenSearch/pull/10753

**Describe alternatives you've considered**

**Additional context**

### Check List
- [x] Backport Labels added.
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by atharvasharma61** [comment]
Test failures will be addressed in the following PR: https://github.com/opensearch-project/performance-analyzer/pull/651

File: src/main/java/org/opensearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java [hunk 1]
```diff
@@ -118,10 +122,15 @@ public void collectMetrics(long startTime) {
                                                 SHARD_REQUEST_CACHE.toString(),
                                                 requestCacheMaxSize);
                                     } catch (Exception e) {
-                                        return new CacheMaxSizeStatus(
```
Comment (psychbot) [inline src/main/java/org/opensearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java:121]: Can you provide more insight as to why do we need to modify this?

Comment (atharvasharma61) [reply src/main/java/org/opensearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java:121]: Reason being, in the 2nd parameter of CacheMaxSizeStatus, We are passing null value but CacheMaxSizeStatus implementation expects it to be non-null.

**Comment by atharvasharma61** [comment]
> @atharvasharma61 thanks for raising this. Could you please add the following details here?
> 
>     1. The changes in the core has introduced this issue. As far as I understood there is a level of nesting being introduced with tiered cache. Please provide the changes for reference.
> 
>     2. Please add the test case to capture such issues in the build iteslf.

Hi Gagan. Thanks for responding. 

1. I have added the relevant PR in the description.
2. This issue already got caught in failed UTs for the corresponding collector. So this case is also covered.

**Comment by Gaganjuneja** [comment]
> > @atharvasharma61 thanks for raising this. Could you please add the following details here?
> > ```
> > 1. The changes in the core has introduced this issue. As far as I understood there is a level of nesting being introduced with tiered cache. Please provide the changes for reference.
> > 
> > 2. Please add the test case to capture such issues in the build iteslf.
> > ```
> 
> Hi Gagan. Thanks for responding.
> 
> 1. I have added the relevant PR in the description.
> 2. This issue already got caught in failed UTs for the corresponding collector. So this case is also covered.

How come it got released then?

**Comment by atharvasharma61** [comment]
> > > @atharvasharma61 thanks for raising this. Could you please add the following details here?
> > > ```
> > > 1. The changes in the core has introduced this issue. As far as I understood there is a level of nesting being introduced with tiered cache. Please provide the changes for reference.
> > > 
> > > 2. Please add the test case to capture such issues in the build iteslf.
> > > ```
> > 
> > 
> > Hi Gagan. Thanks for responding.
> > 
> > 1. I have added the relevant PR in the description.
> > 2. This issue already got caught in failed UTs for the corresponding collector. So this case is also covered.
> 
> How come it got released then?

Looks like it is a miss. Build has been failing for quite some time. PR from 3 months ago: https://github.com/opensearch-project/performance-analyzer/actions/runs/8379459182/job/22946424856

**Review by Gaganjuneja — APPROVED** [review]

**Review by nishchay21 — APPROVED** [review]
